### PR TITLE
Speakers page

### PR DESCRIPTION
**Pull request by MPDR200011**
# Description

Updated speakers page looks. Overall, not many changes, there is a new layout to the items, and the Overlay component has been modified so it can be used by both the speakers and team page. There are a lot of fixed width values for containers as the items in this page are not completely centered like in the team page (anyone has a better solution for this?).

Also encountered a bug on Chrome. The Occupation text can be a bit big and it will enlarge the containing div unless I used `width: min-content` on the containing div, and then it would wrap the text. However, Chrome, passes the enlarged div width to the parent so the grid display can arrange the items, causing it to allocate too much space for the element, ending up with misaligned items. The fix was to just move the `width` property to the direct parent of the Occupation component and then it was fixed. Just wrote this here in case anyone ever encounters this problem again.

# Tasks

- [x] Change page banner title
- [x] Change layout
- [x] Change overlay of the items
- [ ] Add the new content

### CODE REVIEW

**Review by SocksDevil — APPROVED** [review]
:shipit:

**Comment by pedromsfernandes** [comment]
Looking good! I'm curious about the fixed widths, though. Wouldn't bootstrap's Container suffice?

**Comment by MPDR200011** [comment]
> Looking good! I'm curious about the fixed widths, though. Wouldn't bootstrap's Container suffice?

The mockup showed the squares arranged in four columns with the center of the grid aligned with the center of the page, the bootstrap container is too wide for this as we also want the squares justified to the left. So the solution I found was to give the grid a fixed width, as the squares also have a fixed width it is easy to calculate the necessary space.

**Review by pedromsfernandes — APPROVED** [review]

**Review by SantosAntero — APPROVED** [review]
Looks fine!!

**Pull request merged**
