### PR TITLE
Add talk and panel

### PR DESCRIPTION
**Pull request by pedromsfernandes**
# Description

Added new talk, and the internships panel.

# Tasks

- [x] Add Michela Magas' talk
- [x] Add internships panel

### CODE REVIEW

**Comment by SocksDevil** [comment]
The panel is not being rendered. Do you know as to why?

**Comment by pedromsfernandes** [comment]
> The panel is not being rendered. Do you know as to why?

Weird, just tried on my PC and everything looks fine.

**Review by MPDR200011 — APPROVED** [review]
Everything looks good

**Comment by MPDR200011** [comment]
> The panel is not being rendered. Do you know as to why?

It is rendering for me in the preview build, maybe it's something on your side?

**Review by SocksDevil — APPROVED** [review]
Weird, as of right now it shows up :thinking: .

**Pull request merged**
