### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by MPDR200011**
# Description

Implemented team page according to mock-up. In doing so updated the PageBanner component style to now have the gradient, and the Footer component to have the purple background and white foreground. The JSON with the team composition has also been updated, however there are still some member photos missing. 

# Tasks

- [x] Implement new page layout
- [x] Implement new overlay for the members
- [x] Change the team JSON
- [ ] Add missing member photos

# Relevant Notes

- The member "squares" have different colors so they can create a chessboard effect, however, in making the page responsive, each row had to have less columns for smaller screens, thus breaking the effect. I'm not sure how to solve this as the colors are assigned at page generation.

- The mock-up shows the navbar being seamless with the banner gradient, however since the navbar has 0.9 opacity it is not really possible unless the navbar becomes completely opaque (unless I'm missing something). Since this opacity has been added from the last pull request I prefer to only change it after talking with everyone.

- I originally changed the Overlay component directly, however I then noticed that this component is used in other pages. I ended up restoring the old Overlay and created a new MemberOverlay just for this page as I'm not sure how the other pages will be styled. This way the team page uses the new overlay while the other pages keep the old one for now.

### CODE REVIEW

**Comment by SocksDevil** [comment]
>  The member "squares" have different colors so they can create a chessboard effect, however, in making the page responsive, each row had to have less columns for smaller screens, thus breaking the effect. I'm not sure how to solve this as the colors are assigned at page generation.

I dont think it's a bad thing that we have to give up the chessboard effect for smaller screens since we still want to expose the teams social media, and mobile shouldn't have to hover. 
However I don't think your reasoning is truly what's breaking the chessboard effect loss, since I lose the chessboard effect as soon as I enter developer mode, even in a 4k screen. Do you know as to why this is the case?

> The mock-up shows the navbar being seamless with the banner gradient, however since the navbar has 0.9 opacity it is not really possible unless the navbar becomes completely opaque (unless I'm missing something). Since this opacity has been added from the last pull request I prefer to only change it after talking with everyone.

I'll leave this decision to @pedromsfernandes and @SantosAntero 

> I originally changed the Overlay component directly, however I then noticed that this component is used in other pages. I ended up restoring the old Overlay and created a new MemberOverlay just for this page as I'm not sure how the other pages will be styled. This way the team page uses the new overlay while the other pages keep the old one for now.

Perhaps this should be notated down somewhere, in case this is indeed the case, perhaps adding a TODO to the component? Even a comment in the other relevant USs.

Other than that this PR lgtm :+1: , great work!

**Comment by MPDR200011** [comment]
> However I don't think your reasoning is truly what's breaking the chessboard effect loss, since I lose the chessboard effect as soon as I enter developer mode, even in a 4k screen. Do you know as to why this is the case?

Not sure what you mean here. Are you talking about the number of columns decreasing or the transparent overlay disappearing? If it is the latter its because of a media query that detects if the device can hover elements, and if it can't it removes the animations leaving only the name and links.

**Comment by SocksDevil** [comment]
> 
> 
> > However I don't think your reasoning is truly what's breaking the chessboard effect loss, since I lose the chessboard effect as soon as I enter developer mode, even in a 4k screen. Do you know as to why this is the case?
> 
> Not sure what you mean here. Are you talking about the number of columns decreasing or the transparent overlay disappearing? If it is the latter its because of a media query that detects if the device can hover elements, and if it can't it removes the animations leaving only the name and links.

Ah I see what you meant on the message now, it wasn't clear to me. I believe we can deem what you said as a non problem, but I'll let the decision to @pedromsfernandes

**Review by SocksDevil — DISMISSED** [review]

**Comment by pedromsfernandes** [comment]
> The member "squares" have different colors so they can create a chessboard effect, however, in making the page responsive, each row had to have less columns for smaller screens, thus breaking the effect. I'm not sure how to solve this as the colors are assigned at page generation.

I agree with @andrefmrocha here, i think it's a non issue and we shouldn't worry about it.

> The mock-up shows the navbar being seamless with the banner gradient, however since the navbar has 0.9 opacity it is not really possible unless the navbar becomes completely opaque (unless I'm missing something). Since this opacity has been added from the last pull request I prefer to only change it after talking with everyone.

I see two approaches here, we could make the navbar fully opaque, or we could set a prop in order for it to have some opacity when we want it to. Just so we don't forget, the opacity was added because of the slideshow in the landing page, in order for the navbar to blend in with the background.

> I originally changed the Overlay component directly, however I then noticed that this component is used in other pages. I ended up restoring the old Overlay and created a new MemberOverlay just for this page as I'm not sure how the other pages will be styled. This way the team page uses the new overlay while the other pages keep the old one for now.

I checked back and noticed the `Overlay` component was used on the team and speakers page. For the sake of consistency I expect the image department to use the same strategy, but for now, since we don't have the mockups for the speakers page, I agree with your approach.

Apart from this, I noticed you edited the footer's background color directly. This doesn't work since the footer on the landing page has a white background. In order to solve this I'd set a prop on the component in order to toggle the colors between "light" and "dark".

Hopefully we can have @SantosAntero 's feedback on all this.

Everything else looks fine, great work!

**Comment by SantosAntero** [comment]
> The member "squares" have different colors so they can create a chessboard effect, however, in making the page responsive, each row had to have less columns for smaller screens, thus breaking the effect. I'm not sure how to solve this as the colors are assigned at page generation.

I agree with the what has been said, don't worry about this!

> The mock-up shows the navbar being seamless with the banner gradient, however since the navbar has 0.9 opacity it is not really possible unless the navbar becomes completely opaque (unless I'm missing something). Since this opacity has been added from the last pull request I prefer to only change it after talking with everyone.

If changing the navbar opacity to 1.0 makes it so it blends seamlessly with the banner gradient I think we can make it completely opaque without a problem since I think it'll still look good on the landing page! This is, of course to avoid the use of a prop like Pedro said, since the difference between 0.9 and 1.0 opacity doesn't create a relevant effect.

> I checked back and noticed the Overlay component was used on the team and speakers page. For the sake of consistency I expect the image department to use the same strategy, but for now, since we don't have the mockups for the speakers page, I agree with your approach.

@pedromsfernandes I'll make sure the same overlay is used on both pages.

**Comment by MPDR200011** [comment]
Ok, so I followed the suggestions and made gave the footer a prop to switch it between light and dark mode, by default it will be in light mode. And also made the navbar opaque.

**Review by pedromsfernandes — APPROVED** [review]

**Review by SocksDevil — APPROVED** [review]
Lgtm but let's wait on a review from @SantosAntero to merge it.

**Review by SantosAntero — APPROVED** [review]
Looks ready to me!

**Pull request merged**
