### PR TITLE
First Release

### PR DESCRIPTION
**Pull request by pedromsfernandes**
# Description

Final preparations before the first release.

# Tasks

- [x] Hide competition link
- [x] Hide tickets link
- [x] Add CTF link
- [x] Review website behaviour on desktop and mobile devices

### CODE REVIEW

**Comment by MPDR200011** [comment]
All looks good, although I find it a bit weird that the "Bilhetes" link in the navbar takes you to a section on the page with a text saying that we won't want to lose this edition, makes on think like there is something missing. Don't know what others think about this.

**Review by MPDR200011 — DISMISSED** [review]

**Comment by pedromsfernandes** [comment]
> All looks good, although I find it a bit weird that the "Bilhetes" link in the navbar takes you to a section on the page with a text saying that we won't want to lose this edition, makes on think like there is something missing. Don't know what others think about this.

Fair point. Now I think about it I'm not even sure we'll have the event on eventbrite since it's remote. @andrefmrocha can you confirm this?

**Comment by SocksDevil** [comment]
> > All looks good, although I find it a bit weird that the "Bilhetes" link in the navbar takes you to a section on the page with a text saying that we won't want to lose this edition, makes on think like there is something missing. Don't know what others think about this.
> 
> Fair point. Now I think about it I'm not even sure we'll have the event on eventbrite since it's remote. @andrefmrocha can you confirm this?

We'll still have a form of tickets, by the webinar platform

**Comment by pedromsfernandes** [comment]
Alright, then maybe we can replace the text with "Tickets will be available soon"?

**Comment by SocksDevil** [comment]
I agree.

**Review by MPDR200011 — APPROVED** [review]

**Review by SocksDevil — APPROVED** [review]

**Pull request merged**
