### PR TITLE
Panel Page

### PR DESCRIPTION
**Pull request by pedromsfernandes**
# Description

Adapted the session template to allow panels. You can check it out in this path: `/panels/why-red-is-always-sus`.

# Tasks

- [x] Add moderator and list of participants
- [x] Add "Painel" prefix at the program page to make it more explicit
- [ ] Add actual data
- [x] Add correct icon

### CODE REVIEW

**Comment by MPDR200011** [comment]
I noticed that with reduced widths the text of the participants overlaps with their photos. Also, the photos and respective text have a lot of left margin in mobile.

**Review by SocksDevil — CHANGES_REQUESTED** [review]
| I noticed that with reduced widths the text of the participants overlaps with their photos. Also, the photos and respective text have a lot of left margin in mobile.
As @MPDR200011 mentioned, this should be fixed. Let's also ask if @SantosAntero, @catarina03 or @TitoGrine  can provide the icon used for the mockups

**Comment by pedromsfernandes** [comment]
The overlap should be fixed now, and I also added the correct icon.

**Review by SocksDevil — APPROVED** [review]
:rocket:

**Review by SantosAntero — APPROVED** [review]
Looks good!

**Pull request merged**
