### PR TITLE
Fixes for the first release

### PR DESCRIPTION
**Pull request by pedromsfernandes**
# Description

Final fixes before the first release, as reported by other sinf members.

# Tasks

- [x] Remove unused sponsors page
- [x] Remove title from web svg that causes "Untitled-1" to show on hover
- [x] Display workshop speakers
- [x] Update favicon, og_thumbnail
- [x] Add one talk and one workshop

### CODE REVIEW

**Comment by SocksDevil** [comment]
Should we wait upon further changes or are we going to do further PRs?

**Comment by pedromsfernandes** [comment]
If something else comes up I'll use this PR

**Comment by MPDR200011** [comment]
There are new profile pictures in the drive as well as new social media links (from Luis Silva and Miguel Pinto). We can probably take this opportunity to add those.

**Comment by SocksDevil** [comment]
@pedromsfernandes  there are several new talks already available on our personal drive. Might you add them to this PR?

**Comment by SocksDevil** [comment]
> @pedromsfernandes there are several new talks already available on our personal drive. Might you add them to this PR?

There's also a new workshop

**Comment by pedromsfernandes** [comment]
> @pedromsfernandes there are several new talks already available on our personal drive. Might you add them to this PR?

Some of the talks have incomplete information such as the title so I have not added them yet.

**Comment by SocksDevil** [comment]
Also,  I dont think there's any reason to not have the pitch and the interviews showing up as well

**Comment by pedromsfernandes** [comment]
> Also,  I dont think there's any reason to not have the pitch and the interviews showing up as well

Well, I found no information on the drive besides the schedule spreadsheet. I can add them as "default" events though.

**Comment by SocksDevil** [comment]
> > Also,  I dont think there's any reason to not have the pitch and the interviews showing up as well
> 
> Well, I found no information on the drive besides the schedule spreadsheet. I can add them as "default" events though.

Right, but I think we can just prepare from scratch. The pitches we can "steal" last years and interviews we need to prepare something

**Comment by andrefmrocha** [comment]
m«««

**Comment by SocksDevil** [comment]
We do need to "translate" the icons to the new theme. @catarina03 is this doable quickly?

**Review by SocksDevil — DISMISSED** [review]

**Comment by SocksDevil** [comment]
David Amador's talk and Horácio Marques' already have a title, it was only misfilled

**Comment by SocksDevil** [comment]
Another talk will also show up there soon, I hope

**Review by SocksDevil — APPROVED** [review]
Don't think we'll be getting anything new today, so let's :rocket: it

**Review by MPDR200011 — APPROVED** [review]

**Pull request merged**
