### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by pedromsfernandes**
# Description

Updated landing page. Most notably, we now have `react-bootstrap` instead of `reactstrap`. The main reason is that I wanted to use `bootstrap`'s carousel to implement the banner's slideshow, but `reactstrap`'s implementation wouldn't work. Apart from that, `react-bootstrap` is now fully updated to `bootstrap` version 4.5, so `reactstrap` has no real advantage.

# Tasks

- [x] Migrate from `reactstrap` to `react-bootstrap`
- [x] Update color palette
- [x] Add slideshow to banner
- [x] Make navbar a little bit transparent
- [x] Add gradients between sections

### CODE REVIEW

**Review by MPDR200011 — DISMISSED** [review]

**Comment by SocksDevil** [comment]
I have a question regarding the impact of this change. How different will the API be? Much of website components were to be reused, what will be the impact of not changing bootstrap packages?

**Comment by pedromsfernandes** [comment]
> I have a question regarding the impact of this change. How different will the API be? Much of website components were to be reused, what will be the impact of not changing bootstrap packages?

Not sure I completely follow what you're asking, but I already went ahead and updated all of the components to use `react-bootstrap`, and I didn't find many differences. You can check it out yourself by looking at the other pages. They will look kind of funky because of the new palette, but the overall structure didn't change.

**Review by SocksDevil — DISMISSED** [review]

**Comment by SocksDevil** [comment]
Alright thanks for clearing it up. I wouldn't consider this to require a design review so I believe we can merge this down right? If that's the case, press the button

**Comment by pedromsfernandes** [comment]
Since the landing page has some changes such as the slideshow and gradients, I'd really appreciate if @SantosAntero gave his OK just to be sure

**Comment by pedromsfernandes** [comment]
My apologies for the delay. @SantosAntero mentioned the navbar's transparency should be decreased a bit,  so there it is. I think we're ready to merge now!

**Review by SantosAntero — APPROVED** [review]
Everything looks good!

**Review by SocksDevil — APPROVED** [review]
Lgtm :shipit:

**Pull request merged**
