### PR TITLE
Sessions/Interviews page

### PR DESCRIPTION
**Pull request by pedromsfernandes**
# Description

Updated the page for sessions and interviews, since they share the same template. Regarding the mock-ups, I wasn't sure if the red frames around the company logos were supposed to be placeholders or not. I did try to include them but they didn't seem to fit quite well.

Here's two sessions for you to look at: 

* `/sessions/sessao-de-cocktails`
* `/sessions/sessao-de-networking`

# Tasks

- [x] Dark footer
- [x] Banner with gradient
- [x] Remove place since it's online
- [ ] Add data along with the correct images
- [ ] Red frame (?)

### CODE REVIEW

**Review by SocksDevil — CHANGES_REQUESTED** [review]
Lgtm but let's just make sure that these resources of companies that do not sponsors are not released by mistake :sweat_smile: . Might you substitute them with a mockup of sorts? Perhaps NI's logo or smth

**Comment by pedromsfernandes** [comment]
As requested, I've replaced the sponsors information with NI placeholders.

**Review by SocksDevil — APPROVED** [review]
Thanks! Lgtm :shipit:

**Review by SantosAntero — APPROVED** [review]
Looks good, good job!

**Pull request merged**
