### PR TITLE
Program page

### PR DESCRIPTION
**Pull request by pedromsfernandes**
# Description

Updated the styling of the program page. Overall there are only a few changes, such as the ProgramNav and the description togglers. Just a note though: the mock-ups didn't show the colors for the Activities tab, therefore I decided to keep `black` for the visits, and `#350052#` for the sessions.

# Tasks

- [x] Use new color palette
- [x] Adjust program nav
- [x] Description toggler animation
- [x] Use new page banner
- [ ] Update daily themes and respective icons
- [ ] Update schedule

### CODE REVIEW

**Comment by TitoGrine** [comment]
Sorry, didn't realize they were different on last year's website.
I would say either use #FF341F (red) or #350052 (dark purple) for the visits and keep the #FF711F (dark orange) for the sessions. 
Keep up the good work :llama:

**Comment by SocksDevil** [comment]
I was going to request @TitoGrine 's help :sweat_smile: but he helped out right off the bat (thanks for that). It does look ugly in the current color scheme, mind trying out these colors @pedromsfernandes ?

**Comment by pedromsfernandes** [comment]
As per @TitoGrine 's suggestion, sessions now use #FF711F and visits use #FF341F.

**Review by MPDR200011 — APPROVED** [review]
Lgtm

**Review by SantosAntero — APPROVED** [review]
Everything looks fine to me.

**Review by SocksDevil — APPROVED** [review]

**Pull request merged**
